sudo: required
serices:
  - docker

before_install:
  - docker build -t abhilekh7k/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true abhilekh7k/docker-react npm run test -- --coverage