sudo: required
serices:
  - docker

before_install:
  - docker build -t abhilekh7k/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true abhilekh7k/docker-react npm run test -- --coverage
deploy: 
  provider: elasticbeanstalk 
  region: "us-east-2"
  app: "dockerReact"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-988794560488"
  bucket_path: "dockerReact"
  on:
    branch: master
    access_key_id: 
      secure: "$AWS_ACCESS_KEY"
    secret_access_key:
      secure: "$AWS_SECRET_KEY"