sudo: required
serices:
  - docker

before_install:
  - docker build -t abhilekh7k/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true abhilekh7k/docker-react npm run test -- --coverage
deploy: 
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key:
    secure: "$SECRETACCESSKEY" 
  region: "us-east-2"
  app: "dockerReact"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-988794560488"
  bucket_path: "dockerReact"
  on:
    branch: master